# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - docker07022025

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://docker07022025.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_10e7e23c77434d62a94898c5dd03b9b1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_86ddf29dbf2a4c1c8e28cc0f4902bb2b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: docker07022025.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_10e7e23c77434d62a94898c5dd03b9b1 }}/studentperformance1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'docker07022025'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d088b0b1d5434951ac064ec50447f94c }}
        images: 'docker07022025.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_10e7e23c77434d62a94898c5dd03b9b1 }}/studentperformance1:${{ github.sha }}'